name: Generate Language Distribution by Repo
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate dark variant
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/languages-by-repo-dark.svg
          hide-keys: general, contributions, repositories
          colors: dark
          include-title: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate light variant
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/languages-by-repo-light.svg
          hide-keys: general, contributions, repositories
          colors: light
          include-title: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
